# Add a comment
aString: string
anotherString: "another String - changed but not important"

int: 2
float: 1.2

obj:
  some: key
  one: 1
  nested:
    cool: swag
  arr:
  - one
  - two

array:
- one
- two
- three
